### AWS buildspec.yml file for building a Docker image and pushing it to ECR
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - >
        aws ecr get-login-password
        --region $AWS_REGION | docker login
        --username AWS
        --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker web image...
      - >
        docker build
        --platform $BUILD_PLATFORM
        -t $ECR_IMAGE:$ECR_IMAGE_TAG
        --build-arg BASE_IMAGE=$BASE_IMAGE
        --target web
        .
      - echo web image built successfully

  post_build:
    commands:
      - echo tagging web image...
      - >
        docker
        tag $ECR_IMAGE:$ECR_IMAGE_TAG
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_IMAGE:$ECR_IMAGE_TAG
      - echo pushing web image...
      - >
        docker
        push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_IMAGE:$ECR_IMAGE_TAG
      - echo web image pushed successfully
      - echo Build completed on `date`

cache:
  paths:
    - '/root/.docker/**/*'

env:
  variables:
    AWS_ACCOUNT_ID: 208722357485
    BASE_IMAGE: php:8.4.8-fpm
    ECR_IMAGE: fast8d/php-base-web-image
    ECR_IMAGE_TAG: latest
    BUILD_PLATFORM: linux/amd64
