services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    platform: ${BUILD_PLATFORM}
    container_name: ${WEB_CONTAINER_NAME}
    image: ${ECR_WEB_IMAGE}:${ECR_WEB_IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    platform: ${BUILD_PLATFORM}
    container_name: ${WORKER_CONTAINER_NAME}
    depends_on:
      - web
    image: ${ECR_WORKER_IMAGE}:${ECR_WORKER_IMAGE_TAG}
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d
